name: ci

on:
  push:
    branches: main
jobs:  
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version  # Optional: Verify installation  
      - name: Test        
        run: docker-compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"  






#        login:
#          runs-on: ubuntu-latest
#          steps:
#            -
#              name: Login to GitHub Container Registry
#              uses: docker/login-action@v3
#              with:         
#                username: ${{ secrets.DOCKERHUB_USER }}
#                password: ${{ secrets.DOCKERHUB_TOKEN }}
#            - name: Test Docker
#              run : docker-compose run --rm app sh -c "django-admin startproject app ." 
        